### ISSUE TITLE
Includes In cpp files, could be moved to header files

### ISSUE THREAD

**Issue by NicholasLangley** [UCSolarCarTeam/Epsilon-Desktop-Client-Telemetry#3]

**Comment by bill-luu** [comment]
I carried this style from other projects, which also use forward declaration
http://stackoverflow.com/questions/4757565/what-are-forward-declarations-in-c

**Comment by enochtsang** [comment]
The main purpose of forward declares is to speed up compile time. For our projects since they only take a few minutes to compile, it's not a huge deal. But when you work in a company in larger products, good practice for compilation times can save you taking 8 hours to compile compared to just 1 hour.
