### ISSUE TITLE
EpsilonDesktopTelemetry constructor can have more descriptive argument names

### ISSUE THREAD

**Issue by NicholasLangley** [UCSolarCarTeam/Epsilon-Desktop-Client-Telemetry#4]
rather than argc and argv

**Comment by bill-luu** [comment]
I chose `argc` and `argv` because the QApplication class in `EpsilonDesktopTelemetry.cpp` also contains arguments that serve the same role as `argc` and `argv` when normally used in main.

http://doc.qt.io/qt-5/qapplication.html

**Comment by enochtsang** [comment]
argc and argv imo are actually good names. They are very standard in C++ programming. While they are grouped together, because of convention, argc and argv tell you 1. where they are from 2. they are for configuration. Once they are separated and parsed, that's when you want to give more detail about what each individual argument does.
